query allQuizzes {
  allQuizzes {
    id
    title
    description
    time_limit
    is_public
    is_draft
    theme {
      id
      name
    }
    level {
      id
      name
    }
    liked_by {
      id
    }
    questions {
      id
    }
  }
}