query Quiz($id: Int!) {
  quiz(id: $id) {
    id
    title
    description
    image
    time_limit
    is_public
    is_draft
    theme {
      id
      name
    }
    level {
      id
      name
    }
    questions {
      id
      title
      choices {
        id
        description
        is_correct
      }
    }
  }
}
