query PrivateQuizzes($themeId: Int, $levelId: Int) {
  privateQuizzes(themeId: $themeId, levelId: $levelId) {
    id
    title
    description
    image
    time_limit
    theme {
      id
      name
    }
    level {
      id
      name
    }
  }
}
