query GlobalStats {
  globalStats {
    newUsers {
      week
      month
      year
    }
    userGrowth {
      period
      count
    }
    attemptsSuccessRate {
      passed
      failed
      successRate
      total
    }
    averageScore
  }
}
