query GlobalStats {
  globalStats {
    newUsers {
      week
      month
      year
    }
    userGrowth {
      period
      count
    }
    attemptsSuccessRate {
      passed
      failed
      successRate
      total
    }
    averageScore
    topQuizzes {
      quiz {
        id
        title
        level {
          id
          name
        }
        theme {
          id
          name
        }
      }
      attemptCount
    }
    topLevels {
      level {
        id
        name
      }
      attemptCount
    }
    topThemes {
      theme {
        id
        name
      }
      attemptCount
    }
  }
}
