events {}
http {
    server { 
        listen 80;

        location = / {
            return 301 /home-page;
        }
        
        location /graphql {
            proxy_pass http://backend:4000/graphql;
        }
        
        location / {
            proxy_pass http://frontend:3000;
        }
    }
}

# Définit un serveur virtuel
# Ecoute sur le port 80, qui est le port standard du web
# Location = / renvoie sur la /home-page si exactement http://localhost/
# Location /graphql renvoie sur http://backend:4001/graphql
# Location / "catch all"
