events {}
http {
    server {
        listen 80;

        location = / {
            return 301 /home-page;
        }
        
        location /graphql {
            proxy_pass http://backend:4001/graphql;
        }
        
        location / {
            proxy_pass http://frontend:3001;
        }
    }
}