name: Compile and push client and server to production environment

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  client-tests:
    uses: sandrinem72/CDA-CyberQuiz/.github/workflows/test-frontend.yml@main

  e2e-tests:
    uses: sandrinem72/CDA-CyberQuiz/.github/workflows/e2e-tests.yml@main

  build-and-push-server:
    uses: sandrinem72/CDA-CyberQuiz/.github/workflows/build-backend.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: sandrinem72/cyberquiz-back:production

  build-and-push-client:
    needs:
      - client-tests
    uses: sandrinem72/CDA-CyberQuiz/.github/workflows/build-frontend.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: sandrinem72/cyberquiz-front:production


  notify-vps:
    needs:
      - e2e-tests
      - build-and-push-server
      - build-and-push-client
    runs-on: ubuntu-latest
    steps:
      - name : Trigger Webhook on VPS
        run: |
          curl -X POST -H "X-Webhook-Secret: ${{ secrets.WEBHOOK_SECRET }}" https://ops.cyberquiz.culturecook.fr/hooks/redeploy-cyberquiz-production
