name: Compile and push client and server to staging environment

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  client-tests:
    uses: sandrinem72/CDA-CyberQuiz/.github/workflows/test-frontend.yml@dev

  build-and-push-server:
    uses: sandrinem72/CDA-CyberQuiz/.github/workflows/build-backend.yml@dev
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: sandrinem72/cyberquiz-back:staging

  build-and-push-client:
    needs:
      - client-tests
    uses: sandrinem72/CDA-CyberQuiz/.github/workflows/build-frontend.yml@dev
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    with:
      image_name: sandrinem72/cyberquiz-front:staging

  notify-vps:
    needs:
      - build-and-push-server
      - build-and-push-client
    runs-on: ubuntu-latest
    steps:
      - name : Trigger Webhook on VPS
        run: |
          curl -X POST -H "X-Webhook-Secret: ${{ secrets.WEBHOOK_SECRET }}" https://ops.cyberquiz.culturecook.fr/hooks/redeploy-cyberquiz-staging