name: Lint backend

on:
  push:
    branches: [ main, dev ]
    paths: [ 'backend/**' ]

jobs:
  linting-backend :
    name: Lint backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: "2.3.8"
      - name: Run Biome
        run: biome ci .

