name: Test frontend

on:
  push:
    branches: [ main, dev ]
    paths: [ 'frontend/**' ]
  workflow_call:
  # https://docs.github.com/en/enterprise-cloud@latest/actions/how-tos/reuse-automations/reuse-workflows

jobs:
  testing-frontend:
    name: Testing frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: "24.11.0"
    - name: Install Dependencies
      run: npm ci
    - name: Run Jest Tests
      run: npm run test
      